name: Detect New Org Members and Create Issue

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:

jobs:
  check-new-members:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Requests Package
        run: pip install requests

      - name: Run Member Check Script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          ORG_NAME: DevFlow-Project
          REPO_NAME: ISSUE1
        run: python .github/scripts/check_members.py

      - name: Commit Updated Member List
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add members.json
          git commit -m "Update members list" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
